### PR TITLE
Update easy-rsa.rb

### PR DESCRIPTION
**Pull request by lookfirst**

### CODE REVIEW

**Comment by ronaldtse** [comment]
Thank you @lookfirst and very much appreciate the contribution !

It looks like the `inreplace` code should be updated as according to the underlying `easyrsa` version. @jjr840430 could you help test and merge this? Thanks.

**Comment by jjr840430** [comment]
@lookfirst Thanks for your reporting. I will look and let you know.

**Comment by jjr840430** [comment]
@lookfirst That looks good, but it needs to convert all variables for Windows platform to ones for MacOS.
I will merge your request at first and make a new version.

**Comment by lookfirst** [comment]
I had to make a couple other changes. See my fork. Thanks. =)

(sorry, super busy with another thing now)

**Pull request merged**
