### PR TITLE
easy-rsa 3.0.8

### PR DESCRIPTION
**Pull request by ChrisBaker97**
Created with `brew bump-formula-pr`.

### CODE REVIEW

**Comment by ChrisBaker97** [comment]
When attempting to check this locally, I get:

```
$ brew bump-formula-pr --force --write --version=3.0.8 easy-rsa
Warning: These pull requests may be duplicates:
easy-rsa 3.0.8 https://github.com/riboseinc/homebrew-easy-rsa/pull/18
==> Downloading https://github.com/OpenVPN/easy-rsa/archive/v3.0.8.tar.gz
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/9721939a50a850a6861cbb7f16953662d77aa181623cd96ebf85d5073ebf2d0e--easy-rsa-3.0.8.tar.gz
Warning: Cannot verify integrity of 9721939a50a850a6861cbb7f16953662d77aa181623cd96ebf85d5073ebf2d0e--easy-rsa-3.0.8.tar.gz
A checksum was not provided for this resource.
For your reference the SHA-256 is: fd6b67d867c3b8afd53efa2ca015477f6658a02323e1799432083472ac0dd200
==> replace /https:\/\/github\.com\/OpenVPN\/easy\-rsa\/archive\/v3\.0\.6\.tar\.gz/ with "https://github.com/OpenVPN/easy-rsa/archive/v3.0.8.tar.gz"
==> replace "2a87c0c617bbfab556c541b83fa5bfdf1c244bfb16b530ca12efb3d979e85191" with "fd6b67d867c3b8afd53efa2ca015477f6658a02323e1799432083472ac0dd200"
==> try to fork repository with GitHub API
==> git add /usr/local/Homebrew/Library/Taps/riboseinc/homebrew-easy-rsa/Formula/easy-rsa.rb
==> git checkout --no-track -b bump-easy-rsa-3.0.8 origin/master
==> git commit --no-edit --verbose --message='easy-rsa 3.0.8' -- /usr/local/Homebrew/Library/Taps/riboseinc/homebrew-easy-rsa/Formula/easy-rsa.rb
==> git push --set-upstream $HUB_REMOTE bump-easy-rsa-3.0.8:bump-easy-rsa-3.0.8
==> git checkout --quiet -
==> create pull request with GitHub API (base branch: master)

$ brew upgrade easy-rsa
==> Upgrading 1 outdated package:
riboseinc/easy-rsa/easy-rsa 3.0.6 -> 3.0.8
==> Upgrading riboseinc/easy-rsa/easy-rsa 3.0.6 -> 3.0.8
==> Downloading https://github.com/OpenVPN/easy-rsa/archive/v3.0.8.tar.gz
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/9721939a50a850a6861cbb7f16953662d77aa181623cd96ebf85d5073ebf2d0e--easy-rsa-3.0.8.tar.gz
Error: An exception occurred within a child process:
  Utils::Inreplace::Error: inreplace failed
easyrsa3/easyrsa:
  expected replacement of "set_var EASYRSA\t\t\"${0%/*}\"" with "set_var EASYRSA \"/usr/local/opt/easy-rsa/share\""
```

Not sure I know where to take it from here...

**Comment by ronaldtse** [comment]
Thanks @ChrisBaker97 ! @phuonghuynh could you help make this work and merge it? Thanks!

**Comment by ChrisBaker97** [comment]
I tried bumping this to 3.0.7 locally and get the same error. Reinstalling 3.0.6 works.

**Comment by ChrisBaker97** [comment]
This seems to work, but before merging it, someone who knows better than me should consider whether the second and third patch lines could be consolidated by simply patching the `$prog_dir` variable once instead, if that's even still necessary at all.

**Comment by ChrisBaker97** [comment]
My bash is a little rusty, so I wanted to add a test block to hopefully verify that easy-rsa actually operates successfully after patching. I don't know if this is sufficient for that task, but it's what @offbyone used when [submitting easy-rsa to homebrew-core originally](https://github.com/Homebrew/homebrew-core/pull/3462). I honestly can't even recall why I needed easy-rsa installed in the first place, let alone being remotely qualified to hack on it, so I'll turn this apparently working modification over to you guys for further testing and/or tweaking. I do wonder if it would be a good idea to have another go at integrating it into homebrew-core, but I'll admit that I also don't follow everything they apparently wanted changed to make it acceptable for inclusion.

**Comment by ChrisBaker97** [comment]
[I opened another pull request](https://github.com/Homebrew/homebrew-core/pull/64219) to integrate this into homebrew-core, so hopefully that gets approved. If not, I'll post the changes from there as a PR here, to see if you want to integrate them.

**Comment by phuonghuynh** [comment]
Thanks @ChrisBaker97 

I have installed this PR locally and failed at test step after install successful, but manually executing commands used in "test" function works. Could we fix for local test? or we will ignore it?

```
> brew test -v easy-rsa
Error: Testing requires the latest version of riboseinc/easy-rsa/easy-rsa
```

Also, could we fix Hound comments?

cc @ronaldtse

**Comment by ChrisBaker97** [comment]
Hi @phuonghuynh,

I'm not sure we can eliminate all of the Hound comments. If, for example, I change line 15 to:
```ruby
15:              "\tprog_dir=\"#{Formula['easy-rsa'].opt_prefix}/share\""
```
then `brew style` complains:
```
$ brew style riboseinc/easy-rsa/easy-rsa
Formula/easy-rsa.rb:15:39: C: Prefer double-quoted strings inside interpolations.
              "\tprog_dir=\"#{Formula['easy-rsa'].opt_prefix}/share\""
                                      ^^^^^^^^^^

1 file inspected, 1 offense detected, 1 offense auto-correctable
```
So it appears as if Homebrew and Hound prefer the opposite, and I don't see a way to make them both happy. (This was also discussed in #17.)

Regarding whitespace around the `/`, I don't think that's something that _should_ change either. Both of these seem to work and `brew style` doesn't complain:
```ruby
35:     ENV["EASYRSA_PKI"] = testpath + "pki"
35:     ENV["EASYRSA_PKI"] = "#{testpath}/pki"
```
but they're inconsistent with [Homebrew's documentation examples](https://rubydoc.brew.sh/Formula#test-class_method) and [other formulae](https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/cmake.rb), so I'm thinking it's probably best to leave them as is.

I did modify the `test` block in the PR I submitted to `homebrew-core` based on their feedback, which eliminates Hound's objections, simply because the code changes. I'll make that change here as well. (Setting the environment variable actually isn't necessary, since it's simply restating the default.)

```ruby
  test do
    assert_match "init-pki complete", shell_output("#{bin}/easyrsa init-pki")
  end
```

Regarding your test error, I'm unable to duplicate that. Using the code from 7c5be3a:
```
$ brew install riboseinc/easy-rsa/easy-rsa
==> Installing easy-rsa from riboseinc/easy-rsa
==> Downloading https://github.com/OpenVPN/easy-rsa/archive/v3.0.8.tar.gz
Already downloaded: /Users/chris/Library/Caches/Homebrew/downloads/9721939a50a850a6861cbb7f16953662d77aa181623cd96ebf85d5073ebf2d0e--easy-rsa-3.0.8.tar.gz
🍺  /usr/local/Cellar/easy-rsa/3.0.8: 19 files, 105.4KB, built in 3 seconds
$ brew test -v easy-rsa
==> Testing riboseinc/easy-rsa/easy-rsa
/usr/bin/sandbox-exec -f /private/tmp/homebrew20201107-6730-12gpi01.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/riboseinc/homebrew-easy-rsa/Formula/easy-rsa.rb --verbose
==> /usr/local/Cellar/easy-rsa/3.0.8/bin/easyrsa --help

Easy-RSA 3 usage and overview

USAGE: easyrsa [options] COMMAND [command-options]

A list of commands is shown below. To get detailed usage and help for a
command, run:
  ./easyrsa help COMMAND

For a listing of options that can be supplied before the command, use:
  ./easyrsa help options

Here is the list of commands available with a short syntax reminder. Use the
'help' command above to get full usage details.

  init-pki
  build-ca [ cmd-opts ]
  gen-dh
  gen-req <filename_base> [ cmd-opts ]
  sign-req <type> <filename_base>
  build-client-full <filename_base> [ cmd-opts ]
  build-server-full <filename_base> [ cmd-opts ]
  revoke <filename_base> [cmd-opts]
  renew <filename_base> [cmd-opts]
  build-serverClient-full <filename_base> [ cmd-opts ]
  gen-crl
  update-db
  show-req <filename_base> [ cmd-opts ]
  show-cert <filename_base> [ cmd-opts ]
  show-ca [ cmd-opts ]
  import-req <request_file_path> <short_basename>
  export-p7 <filename_base> [ cmd-opts ]
  export-p8 <filename_base> [ cmd-opts ]
  export-p12 <filename_base> [ cmd-opts ]
  set-rsa-pass <filename_base> [ cmd-opts ]
  set-ec-pass <filename_base> [ cmd-opts ]
  upgrade <type>

DIRECTORY STATUS (commands would take effect on these locations)
  EASYRSA: /usr/local/opt/easy-rsa/share
      PKI: /private/tmp/easy-rsa-test-20201107-6731-1yqjj0s/pki



==> /usr/local/Cellar/easy-rsa/3.0.8/bin/easyrsa init-pki

init-pki complete; you may now create a CA or requests.
Your newly created PKI dir is: /private/tmp/easy-rsa-test-20201107-6731-1yqjj0s/pki


```
The error you're getting seems similar to [this guy's situation](https://discourse.brew.sh/t/homebrew-inferring-the-wrong-project-version/4051), for which unfortunately he didn't find a resolution. Perhaps try the new test code, and if that fails for you, maybe someone else can chime in to see if it's happening in their environment as well.

**Comment by ChrisBaker97** [comment]
`easy-rsa` is [now available](https://github.com/Homebrew/homebrew-core/pull/64219) in `homebrew-core`.

**Comment by ronaldtse** [comment]
Thanks for contributing it to https://github.com/Homebrew/homebrew-core/pull/64219 . We'll deprecate this repo.

**Pull request closed without merging**
