### PR TITLE
fixed vars.example

### PR DESCRIPTION
**Pull request by jjr840430**

### CODE REVIEW

**Comment by erikbor** [comment]
@jjr840430 My opinion is that this is not the correct approach. `local var` is a declaration of the `var` variable and not meant for initialisation. In case upstream easy-rsa changes code touching `var` then we need to change the formulae again.

**Comment by jjr840430** [comment]
@erikbor current homebrew is based on the release version of `easy-rsa`.
So it won't be changed even if upstream 'easy-rsa' was changed.
We may initialize `vars` with the default location of `easy-rsa` homebrew path.
If the user sets environment variables to set own values, then it will be overwritten.

**Comment by jjr840430** [comment]
@erikbor I replaced `prog_vars` variable instead `vars`. Can you review it now? Thanks.

**Comment by jjr840430** [comment]
@erikbor Any updates on it?

**Pull request merged**
